version: "3.9"

services:
  spark-master:
    image: balogo-spark-4.0.0:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_ROLE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - "7077:7077"        # Spark master port
      - "8080:8080" 
    volumes:
      - /mnt/c/wsl_mount_point/spark_logs:/mnt/spark_logs   # Persist event logs
      - /mnt/c/wsl_mount_point/spark_data:/mnt/spark_data
    networks:
      - spark-net
  spark-worker-1:
    image: balogo-spark-4.0.0:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_ROLE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=5g
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - spark-master
    ports:
      - "8081:8081" 
    volumes:
      - /mnt/c/wsl_mount_point/spark_logs:/mnt/spark_logs   # Persist event logs
      - /mnt/c/wsl_mount_point/spark_data:/mnt/spark_data
    networks:
      - spark-net

  spark-worker-2:
    image: balogo-spark-4.0.0:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_ROLE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=5g
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - spark-master
    ports:
      - "8082:8081" 
    volumes:
      - /mnt/c/wsl_mount_point/spark_logs:/mnt/spark_logs   # Persist event logs
      - /mnt/c/wsl_mount_point/spark_data:/mnt/spark_data
    networks:
      - spark-net

  spark-history:
    image: balogo-spark-4.0.0:latest
    container_name: spark-history
    hostname: spark-history
    environment:
      - SPARK_ROLE=history
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - "18080:18080"       # Spark history server UI
    depends_on:
      - spark-master
    volumes:
      - /mnt/c/wsl_mount_point/spark_logs:/mnt/spark_logs   # Persist event logs
      - /mnt/c/wsl_mount_point/spark_data:/mnt/spark_data
      - ./resources/spark/conf/spark-history-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    networks:
      - spark-net
networks:
  spark-net:
    driver: bridge
